baseURL: https://monsters-api.netlify.app/
languageCode: en-us
title: My New Hugo Site
disableKinds:
- sitemap
taxonomies:
  generation: generations
caches:
  getresource:
    maxAge: 24h
outputs:
  home:
  - JSON
  term:
  - JSON